version: '3.1'

services:

  db:
    image: mysql:5.7
    volumes:
      - /host/folder/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hNTTP5ANzM@C
      MYSQL_DATABASE: redmine

  redmine:
    image: redmine_vsst
    volumes:
      - /host/folder/redmine:/usr/src/redmine/files
    depends_on:
      - db
    restart: always
    ports:
      - 80:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: hNTTP5ANzM@C
      REDMINE_SECRET_KEY_BASE: supersecretkey

volumes:
  /host/folder